name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      UPLOAD_KEYSTORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get LTW
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          repo: artdeell/LTW
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create out directory
        run: mkdir out
      - name: Build Publishing .aab
        if: github.repository_owner == 'MojoLauncher' && github.ref_name == 'v3_openjdk'
        run: |
          gradle :app_pojavlauncher:bundleFullGplay
          mv app_pojavlauncher/build/outputs/bundle/fullGplay/app_pojavlauncher-full-gplay.aab out/app-gplay.aab

      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleFullDebug
          mv app_pojavlauncher/build/outputs/apk/full/debug/app_pojavlauncher-full-debug.apk out/app-debug.apk

      - name: Build Debug .apk (No runtime)
        run: |
          gradle :app_pojavlauncher:assembleNoruntimeDebug
          mv app_pojavlauncher/build/outputs/apk/noruntime/debug/app_pojavlauncher-noruntime-debug.apk out/app-debug-noruntime.apk

      - name: Gen md5sums
        run: |
          md5sum out/app-debug.apk > out/app-debug.md5
          md5sum out/app-debug-noruntime.apk > out/app-debug-noruntime.md5

      # Publish to a stable 'nightly' GitHub Release to avoid artifact quota limits
      - name: Publish Nightly Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          draft: false
          prerelease: true
          generate_release_notes: false
          files: |
            out/app-debug.apk
            out/app-debug.md5
            out/app-debug-noruntime.apk
            out/app-debug-noruntime.md5
            out/app-gplay.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload onto the Google Play testing track
        continue-on-error: true
        if: github.repository_owner == 'MojoLauncher' && github.ref_name == 'v3_openjdk'
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_JSON }}
          packageName: git.artdeell.mojo
          releaseFiles: out/app-gplay.aab
          track: internal
          inAppUpdatePriority: 5
